# Generated by Django 4.1.1 on 2022-11-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.TextField(blank=True)),
                ('messages_sent', models.IntegerField(blank=True)),
            ],
        ),
    ]
