# Generated by Django 4.1.1 on 2022-10-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SISClass',
            new_name='LutherClass',
        ),
    ]
