# Generated by Django 4.1.1 on 2022-10-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lutherclass',
            name='CatalogNumber',
            field=models.IntegerField(default=0),
        ),
    ]
