# Generated by Django 4.1.1 on 2022-10-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studybuddy', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='classes',
            field=models.ManyToManyField(to='studybuddy.lutherclass'),
        ),
    ]
