# Generated by Django 4.1.1 on 2022-11-01 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studybuddy", "0005_friendslist_friendrequest"),
    ]

    operations = [
        migrations.RemoveField(model_name="friendslist", name="friends",),
        migrations.RemoveField(model_name="friendslist", name="user",),
        migrations.AddField(
            model_name="profile",
            name="friends_list",
            field=models.ManyToManyField(
                blank=True, related_name="friends_list", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(name="FriendRequest",),
        migrations.DeleteModel(name="FriendsList",),
    ]
