# Generated by Django 4.1.1 on 2022-11-04 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studybuddy", "0007_friendrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeDate", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "groupUsers",
                    models.ManyToManyField(
                        related_name="other_users_joining", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "post_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_author",
                        to="studybuddy.profile",
                    ),
                ),
                (
                    "studyClass",
                    models.ManyToManyField(blank=True, to="studybuddy.class"),
                ),
            ],
        ),
    ]
