# Generated by Django 4.2.dev20220603193729 on 2022-11-04 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studybuddy", "0007_friendrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeDate", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(max_length=200)),
                (
                    "groupUsers",
                    models.ManyToManyField(
                        related_name="other_users_attending",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("studyClass", models.ManyToManyField(to="studybuddy.lutherclass")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timeDate", models.DateTimeField(auto_now=True)),
                ("location", models.CharField(max_length=200)),
                (
                    "groupUsers",
                    models.ManyToManyField(
                        related_name="other_users_joining", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "requests",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_want_to_join",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("studyClass", models.ManyToManyField(to="studybuddy.lutherclass")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
