# Generated by Django 4.2.dev20220603193729 on 2022-11-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0008_models_for_studypost_studysession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studypost",
            name="studyClass",
            field=models.ManyToManyField(to="studybuddy.class"),
        ),
        migrations.AlterField(
            model_name="studysession",
            name="studyClass",
            field=models.ManyToManyField(to="studybuddy.class"),
        ),
    ]
