# Generated by Django 4.2.dev20220603193729 on 2022-11-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0009_alter_studypost_studyclass_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studypost",
            name="description",
            field=models.TextField(default="", max_length=500),
        ),
    ]
