# Generated by Django 4.1.1 on 2022-11-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0009_scheduleclass"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="schedule",
            field=models.ManyToManyField(blank=True, to="studybuddy.scheduleclass"),
        ),
    ]
