# Generated by Django 4.2.dev20220603193729 on 2022-11-07 04:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0010_studypost_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studypost",
            name="timeDate",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
