# Generated by Django 4.1.1 on 2022-11-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0010_profile_schedule"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="schedule",),
    ]
