# Generated by Django 4.1.1 on 2022-11-05 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studybuddy", "0012_profile_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleclass",
            name="user",
            field=models.ManyToManyField(
                blank=True, related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
