# Generated by Django 4.1.1 on 2022-11-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0013_scheduleclass_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="schedule",),
    ]
