# Generated by Django 4.1.1 on 2022-11-05 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0015_schedule"),
    ]

    operations = [
        migrations.RemoveField(model_name="scheduleclass", name="user",),
    ]
