# Generated by Django 4.1.1 on 2022-11-05 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0016_remove_scheduleclass_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Schedule",),
        migrations.DeleteModel(name="ScheduleClass",),
    ]
