# Generated by Django 4.1.1 on 2022-11-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0018_scheduleclass"),
    ]

    operations = [
        migrations.RemoveField(model_name="scheduleclass", name="classes_owner",),
    ]
