# Generated by Django 4.1.1 on 2022-11-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0022_scheduleclass_classes_owner"),
    ]

    operations = [
        migrations.DeleteModel(name="StudyPost",),
    ]
