# Generated by Django 4.1.1 on 2022-11-07 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0023_delete_studypost"),
    ]

    operations = [
        migrations.DeleteModel(name="Mnemonics",),
    ]
