# Generated by Django 4.1.1 on 2022-11-07 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0026_studypost"),
    ]

    operations = [
        migrations.DeleteModel(name="Mnemonics",),
    ]
