# Generated by Django 4.1.1 on 2022-11-09 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0028_studysession"),
    ]

    operations = [
        migrations.DeleteModel(name="StudyPost",),
    ]
