# Generated by Django 4.1.1 on 2022-11-09 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studybuddy", "0029_delete_studypost"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timeDate",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=500),
                ),
                (
                    "groupUsers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="other_users_joining",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="users_want_to_join",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "studyClass",
                    models.ManyToManyField(blank=True, to="studybuddy.scheduleclass"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_class",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_class",
                        to="studybuddy.scheduleclass",
                    ),
                ),
            ],
        ),
    ]
