# Generated by Django 4.1.1 on 2022-11-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studybuddy", "0031_alter_studypost_user_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studypost",
            name="user_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_class",
                to="studybuddy.scheduleclass",
            ),
        ),
    ]
